### ISSUE TITLE
Error when requesting XML

### ISSUE THREAD

**Issue by blackerby** [christopherkenny/congress#17]
Greetings! I was really pleased to come across this package. It looks useful and ergonomic for working with the Congress.gov API.

As I was getting acquainted with it, I encountered this error:

```r
library(congress)

set_congress_key("DEMO_KEY")

cong_congress(format = "xml")

#> Error in `dplyr::all_of()`:
#> ! Can't subset columns that don't exist.
#> ✖ Column `sessions` doesn't exist.
```
This was obviously just for the `congress` endpoint, but I suspect other endpoints may have the same issue, assuming I've used the function correctly. It looks like the data wrangling that needs to happen when an XML response is requested is different from what needs to happen with JSON.

The contents of [this gist](https://gist.github.com/blackerby/894e44a535df82137a84c7e1b132bdc2) show my experimentation with rectangling the XML similarly to how the JSON is treated. R is not my strong suit (but I'm working on it), so there may be a cleaner way to achieve the same result.

If the above is not the expected behavior, and if you've got an easy fix in mind, feel free to adapt the code in that gist if it's useful. I'd also be happy to dig into this further with an eye towards submitting a PR if that would be helpful.

Like I said above, I'm excited about this package. I've been looking across various programming language communities for a complete Congress.gov API client; I should have known I'd find it in the R community!

**Comment by christopherkenny** [comment]
Thanks for pointing this out and for your example of wrangling it! 

It seems like the best way for me to address this would be to request only the `.json` type if `clean = TRUE`, since the data returned is the same either way, just the structure differs. Since the returned object is *supposed* to be a `tibble` if `clean = TRUE`, then the requested type doesn't impact anything on the user side when `clean = TRUE`.

Would that type of solution work for you or do you need both the `.xml` file to be downloaded and a clean `tibble` to be returned?

**Comment by blackerby** [comment]
That type of solution would certainly work for me. Thank you!
